validate de otro repo

diff --git a/.github/workflows/ValidacionNueva.yml b/.github/workflows/ValidacionNueva.yml
--- a/.github/workflows/ValidacionNueva.yml
+++ b/.github/workflows/ValidacionNueva.yml
@@ -25,6 +25,7 @@ jobs:
       - name: Validate Diagram Relations
         run: |
           
+          /*
           # We define the required patterns as Regex
           # 1. LoadBalancer -> Server pattern
           # 2. Server -> Database pattern
@@ -45,33 +46,34 @@ jobs:
           grep -q "HTTPS" $DIAGRAM_FILE || { echo "❌ Missing HTTPS definition"; exit 1; }
           
           echo "✅ Architecture structure matches requirements."
-          
+          */
 
         #echo "Validating mandatory relationships..."
-         # MISSING=0
-
+          MISSING=0
+  
           # Array of mandatory strings to find in the diagrams folder
-         # RELATIONS=(
-           # '"LoadBalancer" ..> "Monitor"'
-           # '"Servidor1RueditasAmigas" ..> "Monitor"'
-           # '"Servidor2RueditasAmigas" ..> "Monitor"'
-           # '"ServidorCacheGeolocalizacion" ..> "Monitor"'
-          # '"ServidorReservas" ..> "Monitor"'
-           # '"DevOp" --> "Monitor" : HTTPS'
-          #)
-
-          #for rel in "${RELATIONS[@]}"; do
+          RELATIONS=(
+            '"LoadBalancer" ..> "Monitor"'
+            '"Servidor1RueditasAmigas" ..> "Monitor"'
+            '"Servidor2RueditasAmigas" ..> "Monitor"'
+            '"ServidorCacheGeolocalizacion" ..> "Monitor"'
+           '"ServidorReservas" ..> "Monitor"'
+            '"DevOp" --> "Monitor" : HTTPS'
+          )
+  
+          for rel in "${RELATIONS[@]}"; do
             # Search recursively in the diagrams folder
-           # if ! grep -rqF "$rel" diagrams/; then
-            #  echo "❌ CRITICAL: Missing relation: $rel"
-            #  MISSING=$((MISSING+1))
-           # fi
-          #done
-
-          #if [ $MISSING -ne 0 ]; then
-           # echo "Validation failed: $MISSING relations missing."
-            #exit 1
-         # fi
+            if ! grep -rqF "$rel" diagrams/; then
+              echo "❌ CRITICAL:
+              Missing relation: $rel"
+              MISSING=$((MISSING+1))
+            fi
+          done
+  
+          if [ $MISSING -ne 0 ]; then
+            echo "Validation failed: $MISSING relations missing."
+            exit 1
+          fi
 
       - name: Generate PlantUML Diagrams
         uses: Timmy/plantuml-action@v1
